### ISSUE TITLE
Can give some examples? I want to render image in browser.

### ISSUE THREAD

**Issue by bonafideyan** [yegor-pelykh/image-in-browser#1]
thanks for your great work.

**Comment by yegor-pelykh** [comment]
Hi @bonafideyan,
Did you have a chance to see an example from the README?
https://github.com/yegor-pelykh/image-in-browser#example

If this example is not enough, please let me know what exactly you would like to see in the examples?

**Comment by bonafideyan** [comment]
nice if add a example that render MemoryImage into canvas, I try it but still not work, please help fix.


```
      var memoryImage = decodeNamedImage(e.target.response, 'b.tiff')

      var canvas = document.createElement('canvas')
      canvas.width = memoryImage.width
      canvas.height = memoryImage.height
      var ctx = canvas.getContext('2d')
      var img = ctx.createImageData(memoryImage.width, memoryImage.height)
      
      var rgba = UTIF.toRGBA8(memoryImage)
      img.data.set(rgba) 
      ctx.putImageData(img, 0, 0) 
      
      document.getElementById('tiff-inner-container').appendChild(canvas)
```

it works, but not properly, the key problem is convert MemoryImage to RGBA8 array.

**Comment by yegor-pelykh** [comment]
I see the main problem with how you get the byte array from the MemoryImage object. Getting raw bytes doesn't require any third party packages like UTIF, so instead of:
`var rgba = UTIF.toRGBA8(memoryImage)`
you can just do this:
`var rgba = memoryImage.getBytes(ColorModel.rgba)`

A complete use case for canvas that works for me (in Angular project):
```js

// Loading TIFF file contents
const response = await lastValueFrom(this.http.get('../assets/moon.tif', {
      observe: 'response',
      responseType: 'arraybuffer',
}));

// Decoding contents into MemoryImage
const memoryImage = decodeImage(response.body);

// Creating canvas and setting its width and height
const canvas = document.createElement('canvas');
canvas.width = memoryImage.width
canvas.height = memoryImage.height

// Getting context
const ctx = canvas.getContext('2d');

// Creation of ImageData based on MemoryImage
const imageData = ctx.createImageData(memoryImage.width, memoryImage.height);
const rawBytes = memoryImage.getBytes(ColorModel.rgba);
imageData.data.set(rawBytes);

// Putting ImageData into context
ctx.putImageData(imageData, 0, 0);

// Adding canvas to the tree
document.body.appendChild(canvas);
```

This is very similar to your example.
You can only replace the line for getting the contents of the file with the one in your example, something like:
```js
const memoryImage = decodeNamedImage(e.target.response, 'b.tiff');
```

Please let me know if this helped you.

**Comment by yegor-pelykh** [comment]
And I would really like to post more examples in my README, the only problem is two things:
- I don’t really know yet what kind of functionality users would like to see described in the examples, since the functionality of the package is quite wide
- need to find more time for it

But I promise that I will do my best 🙂

**Comment by bonafideyan** [comment]
Got it! Thank you very much!

**Comment by yegor-pelykh** [comment]
@bonafideyan I would be very grateful if you support this by starring this repository.
