### ISSUE TITLE
The gif size becomes much larger after cropping

### ISSUE THREAD

**Issue by jinjiebang** [yegor-pelykh/image-in-browser#7]
Cropped image: https://github.com/user-attachments/assets/b6dcc0c2-d64e-45fc-a7b2-23562c0dcbb1
Crop it into a square with the same width and height, without scaling. The original size is more than 600k, and the cropped size is 5mb.

      const cropGif = async () => {
        const buffer = await file.arrayBuffer();
        let image = decodeGif({ data: new Uint8Array(buffer) });
        image = image.convert({ numChannels: 4 });
        image = Transform.copyCrop({
          image,
          rect: Rectangle.fromXYWH(scaledCropX, scaledCropY, scaledCropWidth, scaledCropHeight),
        });
        const output = encodeGif({ image });
        return new Blob([output.buffer]);
      };

**Comment by yegor-pelykh** [comment]
Hi @jinjiebang!
Please try the latest release [v3.2.1](https://github.com/yegor-pelykh/image-in-browser/releases/tag/v3.2.1).
After some fixes the size should be smaller (up to 2.6 MB), but I understand that it is still larger than the original size.
The original GIF file will be smaller in any case, because the GIF animation encoder doesn't create delta frames that encode only the changed pixels.

**Comment by yegor-pelykh** [comment]
Since there were no additional objections or clarifications, I will close the topic.
